name: Web

on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Switch node version
        shell: bash -l {0}
        run: nvm install
      - name: Install
        run: npm ci
        working-directory: ./web
      - name: Build
        run: npm run build
        working-directory: ./web
      - name: Deploy
        if: github.ref == 'refs/head/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./web/build
          CLEAN: true
